version: '3.8'

services:
  api:
    ports:
      - 8000:8000
    volumes:
      - "./api/src:${APP_DIR}"

  scheduler:
    volumes:
      - "./scheduler/src:${APP_DIR}"

  notify_db:
    ports:
      - 5432:5432
