name: Python application

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flake_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install wemake-python-styleguide dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 wemake-python-styleguide

    - name: Lint with wemake-python-styleguide  (TODO не уверен в работе --format=html --htmldir=flake-report)
      run: |
        flake8 . 

    - name: Upload flake-report
      uses: actions/upload-artifact@v2
      with:
        name: flake-report
        path: flake-report

  mypy_etl_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install -r requirements.txt
    - name: mypy
      run: |
        mypy . --config-file pyproject.toml


  send_message:
    runs-on: ubuntu-latest
    needs: [flake_check, mypy_etl_check, mypy_db_tests_check, mypy_ugc_check]
    steps:
      - name: if success
        if: ${{ success() }}
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Success checks. ${{ github.workflow }}.
            Repository: ${{ github.repository }}
            From: ${{ github.actor }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
               - name: Notify on Failure
      - name: if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Fail checks. ${{ github.workflow }}.
            Repository: ${{ github.repository }}
            From: ${{ github.actor }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}